<?php
require_once __DIR__ . '/includes/config.php';
$meta = page_meta(['title' => 'Contact Yoga Prosperity Model | Pune', 'description' => 'Contact the Yoga Prosperity Model team to discuss yoga business programs, mentorship and community membership.', 'path' => '/contact/']);
$structuredData = [breadcrumb_schema([['Home', '/'], ['Contact', '/contact/']])];
$name = trim((string)($_GET['name'] ?? '')); $email = trim((string)($_GET['email'] ?? '')); $phone = trim((string)($_GET['phone'] ?? '')); $message = trim((string)($_GET['message'] ?? '')); $program = trim((string)($_GET['program'] ?? ''));
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero"><div><p class="breadcrumbs"><a href="/">Home</a> / Contact</p><h1>Start a<br><em>conversation.</em></h1></div><p>Tell us about your yoga journey and the kind of growth you are working toward. Our team will follow up personally.</p></section>
<section class="content-section contact-page"><div><p class="eyebrow">Contact details</p><h2>We are here to help.</h2><div class="contact-details"><a href="tel:+917420087709">+91 74200 87709</a><a href="mailto:support@yogaprosperitymodel.com">support@yogaprosperitymodel.com</a><p>Uday Hill Top Residency<br>Ravet, Pune – 412101</p></div><div class="notice">Online payment is not active yet. Your team conversation comes first.</div></div><form class="contact-form" action="mailto:support@yogaprosperitymodel.com" method="post" enctype="text/plain"><label>Name<input type="text" name="name" value="<?= e($name) ?>" placeholder="Your full name" required></label><label>Email<input type="email" name="email" value="<?= e($email) ?>" placeholder="you@example.com" required></label><label>Phone<input type="tel" name="phone" value="<?= e($phone) ?>" placeholder="+91"></label><label>Program of interest<input type="text" name="program" value="<?= e($program) ?>" placeholder="Rajat or Vajra Sangh"></label><label>How can we help?<textarea name="message" rows="5" placeholder="Tell us about your goals"><?= e($message) ?></textarea></label><button type="submit">Send enquiry <span>↗</span></button></form></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
