<?php
require_once __DIR__ . '/includes/config.php';
$current = 'programs';
$meta = page_meta(['title' => 'Yoga Teacher Business Programs | Yoga Prosperity Model', 'description' => 'Compare Rajat Sangh foundation learning and Vajra Sangh advanced mentorship for yoga teachers building sustainable programs and careers.', 'path' => '/programs/']);
$faqs = [
    ['Which Yoga Prosperity Model program should I choose?', 'Rajat Sangh is the foundation option for teachers learning business essentials through recorded lessons, weekly guidance and community. Vajra Sangh is for established teachers seeking deeper one-to-one mentorship and collaborative development.'],
    ['Are the yoga business programs online?', 'Both pathways include online learning or mentoring. Exact session timing, access and any collaborative in-person experience are confirmed before enrolment.'],
    ['Do the programs guarantee income?', 'No. The programs provide education, mentoring and implementation support. Results depend on each teacher’s experience, decisions, execution and market conditions.'],
    ['Can I speak with someone before choosing?', 'Yes. Use the contact page to request a 15-minute clarity conversation about your goals, experience and preferred support level.'],
];
$structuredData = [breadcrumb_schema([['Home', '/'], ['Programs', '/programs/']]), faq_schema($faqs)];
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero page-hero-visual"><div><p class="breadcrumbs"><a href="<?= e(site_path()) ?>">Home</a> / Programs</p><h1>Choose your<br><em>growth path.</em></h1></div><p>Two levels of learning, implementation and mentorship for yoga teachers at different stages of their journey.</p><div class="page-hero-image"><img src="<?= e(asset_url('images/trainer-community-meetup-v1.jpg')) ?>" fetchpriority="high" decoding="async" srcset="<?= e(responsive_srcset('trainer-community-meetup-v1.jpg')) ?>" sizes="(max-width: 768px) 100vw, 768px" alt="Prabhu Zunja with a supportive community of yoga teachers" width="1536" height="1024"><span>Learn. Implement. Grow.</span></div></section>
<section class="plans section"><div class="plan-grid"><article class="plan-card blue"><div class="plan-scene"><img src="<?= e(asset_url('images/rajat-recorded-lectures-v1.jpg')) ?>" srcset="<?= e(responsive_srcset('rajat-recorded-lectures-v1.jpg')) ?>" sizes="(max-width: 768px) 100vw, 768px" alt="Rajat Sangh recorded lecture library" width="1536" height="1024" loading="lazy"><span>Recorded lecture library</span></div><p>Silver membership</p><h3>Rajat Sangh</h3><div class="price">₹6,999<small>/ year</small></div><ul><li>12 recorded lecture courses</li><li>30-day business hackathon</li><li>Weekly Q&amp;A and support</li><li>Accountability community</li></ul><a href="<?= e(site_path('programs/rajat-sangh')) ?>">View full program <span>↗</span></a></article><article class="plan-card dark"><div class="plan-scene"><img src="<?= e(asset_url('images/trainer-mentoring-v1.jpg')) ?>" srcset="<?= e(responsive_srcset('trainer-mentoring-v1.jpg')) ?>" sizes="(max-width: 768px) 100vw, 768px" alt="Focused personal mentoring with Prabhu Zunja" width="1536" height="1024" loading="lazy"><span>Personal guidance</span></div><p>Diamond mentorship</p><h3>Vajra Sangh</h3><div class="price">₹99,999<small>/ year</small></div><ul><li>Everything in Rajat Sangh</li><li>One-to-one coaching</li><li>Collaborative retreat design</li><li>3-year certification path</li></ul><a href="<?= e(site_path('programs/vajra-sangh')) ?>">View full program <span>↗</span></a></article></div><p class="plan-note">Final inclusions and policies will be confirmed before payment integration is activated.</p></section>
<section class="cta-band"><h2>Not sure which<br>Sangh fits?</h2><a class="button" href="<?= e(site_path('contact')) ?>">Ask our team <span>↗</span></a></section>
<section class="faq section program-faq"><div><p class="eyebrow">Compare with clarity</p><h2>Program<br><em>questions.</em></h2><p class="faq-intro">Use these answers to understand the two pathways before speaking with the team.</p></div><div class="accordions"><?php foreach ($faqs as $index => $faq): ?><details <?= $index === 0 ? 'open' : '' ?>><summary><?= e($faq[0]) ?><span>+</span></summary><p><?= e($faq[1]) ?></p></details><?php endforeach; ?></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
