<?php
require_once __DIR__ . '/includes/config.php';
$current = 'method';
$meta = page_meta(['title' => 'Yoga Prosperity Method | Build Your Yoga Business', 'description' => 'A practical framework for yoga teachers: positioning, signature programs, ethical marketing, confident sales and sustainable delivery.', 'path' => '/yoga-prosperity-method/']);
$faqs = [
    ['What is the Yoga Prosperity Method?', 'It is a five-stage business framework for yoga teachers covering purpose and niche, signature-program design, positioning, ethical marketing and enrolment, and sustainable delivery.'],
    ['Is the method only for online yoga teachers?', 'No. The principles can support online, in-person or blended yoga offers because they focus on audience clarity, program structure, communication and participant experience.'],
    ['Does the method replace yoga training?', 'No. It supports the business and delivery side of a yoga career. Teachers remain responsible for practising within their qualifications and professional scope.'],
    ['How can I learn and implement the method?', 'Rajat Sangh offers a recorded foundation with weekly guidance and community. Vajra Sangh adds deeper one-to-one mentoring for established teachers.'],
];
$structuredData = [breadcrumb_schema([['Home', '/'], ['Yoga Prosperity Method', '/yoga-prosperity-method/']]), faq_schema($faqs)];
require __DIR__ . '/includes/header.php';
?>
<section class="page-hero page-hero-visual"><div><p class="breadcrumbs"><a href="<?= e(site_path()) ?>">Home</a> / Our Method</p><h1>Wisdom into<br><em>action.</em></h1></div><p>A clear business path for yoga teachers who want to serve deeply, communicate confidently and grow sustainably.</p><div class="page-hero-image focus-right"><img src="<?= e(asset_url('images/trainer-business-planning-v1.jpg')) ?>" fetchpriority="high" decoding="async" srcset="<?= e(responsive_srcset('trainer-business-planning-v1.jpg')) ?>" sizes="(max-width: 768px) 100vw, 768px" alt="Prabhu Zunja planning a practical yoga business strategy" width="1536" height="1024"><span>Clarity into strategy</span></div></section>
<section class="content-section"><p class="eyebrow">The framework</p><h2>Five stages of purposeful growth.</h2><div class="feature-list"><article><span>01</span><h3>Purpose & niche</h3><p>Define the people you are best equipped to help and the transformation your work creates.</p></article><article><span>02</span><h3>Signature program</h3><p>Package your knowledge into a structured journey with clear outcomes and delivery.</p></article><article><span>03</span><h3>Positioning & message</h3><p>Express your expertise in language that the right students can understand and trust.</p></article><article><span>04</span><h3>Marketing & enrolment</h3><p>Build a repeatable, ethical system for visibility, conversations and confident sales.</p></article><article><span>05</span><h3>Delivery & community</h3><p>Create excellent student experiences, measure outcomes and grow through referrals.</p></article><article><span>∞</span><h3>Implementation</h3><p>Use accountability, weekly guidance and community support to turn learning into action.</p></article></div></section>
<section class="content-section"><div class="prose"><p class="eyebrow">The method in one sentence</p><div class="answer-box"><strong>Clear, responsible growth</strong><p>The Yoga Prosperity Method helps yoga teachers turn expertise into a focused offer, communicate it responsibly, enrol suitable learners and deliver an experience that can grow through evidence and referrals.</p></div></div></section>
<section class="cta-band"><h2>Choose the support<br>that fits your stage.</h2><a class="button" href="<?= e(site_path('programs')) ?>">Explore programs <span>→</span></a></section>
<section class="faq section program-faq"><div><p class="eyebrow">Method explained</p><h2>Common<br><em>questions.</em></h2><p class="faq-intro">Understand what the framework does and where it fits in a yoga career.</p></div><div class="accordions"><?php foreach ($faqs as $index => $faq): ?><details <?= $index === 0 ? 'open' : '' ?>><summary><?= e($faq[0]) ?><span>+</span></summary><p><?= e($faq[1]) ?></p></details><?php endforeach; ?></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
